name: Python package

on: 
  pull_request:
    branches: [master]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4

        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -r requirements.txt

      - name: Test with pytest
        working-directory: ./app
        run: |
          pytest
